version: '3'

services:
  pass-gym-pg:
    image: bitnami/postgresql
    port:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=gymdb